### PR TITLE
feat: re-organize deps

### PR DESCRIPTION
**Pull request by lfender6445**
## Background

- fix issue around peer deps / react mismatch

### CODE REVIEW

**Comment by riskalyze-github** [comment]
:next_track_button:️&nbsp; Latest preview version: <code>v0.0.0-lf-peer-deps-issue.29</code>
:white_check_mark:&nbsp; Merging this PR now will publish the following release:
# [9.16.0](https://github.com/riskalyze/calendar/compare/v9.15.11...v9.16.0) (2021-12-21)


### Features

* re-organize deps ([d84edd5](https://github.com/riskalyze/calendar/commit/d84edd5aa3756f7b90e2def51fd4a609f05c254f))

**Review by ostlerp — COMMENTED** [review]
Looks good but not sure how to verify these changes

**Review by ostlerp — APPROVED** [review]
Scratch that, I did actually verify since this was included in the react-ui PR

**Pull request merged**
